## üìÅ Criando a Base de Dados que possui apenas os cursos de Computa√ß√£o 

#### (APENAS PARA VISUALIZA√á√ïES DE DADOS)

### 1Ô∏è‚É£ Vis√£o Geral dos Dados

In [1]:
import pandas as pd

# L√™ o arquivo Excel
df = pd.read_excel('dados_UFV_Geral_Limpo.xlsx', engine='openpyxl')

# Visualiza as primeiras linhas
df.head()

,Identificador,Ano_Nascimento,Sexo,Campus,Curso_Identificador,Curso,UF_Nascimento,Municipio_Nascimento,Admissao,Saida,...,End_Municipio,End_UF,Intervalo_ENEM,Intervalo_CRA,Regiao_Nascimento,Regiao_End,Intervalo_Ano_Nascimento,Ano_Admissao,Ano_Saida,entrada_pandemia
0,71447,1989.0,M,CAV,1110,CAV - Bacharelado em Educa√ß√£o F√≠sica,MG,Erv√°lia,2009/1,2013/2,...,Ervalia,MG,NaN,80.0-90.0,Sudeste,Sudeste,1980-1989,2009,2013.0,Nao
1,137734,1998.0,M,CAV,1123,CAV - F√≠sica,SP,Sorocaba,2017/1,2023/2,...,Votorantim,SP,600.0-700.0,70.0-80.0,Sudeste,Sudeste,1990-1999,2017,2023.0,Nao
2,71124,1989.0,M,CAV,1108,CAV - Ci√™ncias Econ√¥micas,MG,Sete Lagoas,2009/1,2009/1,...,Ouro Branco,MG,NaN,0-10,Sudeste,Sudeste,1980-1989,2009,2009.0,Nao
3,77401,1991.0,M,CAV,1143,CAV - Licenciatura em F√≠sica,MG,Vi√ßosa,2010/1,2010/2,...,Paula C√¢ndido,MG,600.0-700.0,10.0-20.0,Sudeste,Sudeste,1990-1999,2010,2010.0,Nao
4,90844,1992.0,F,CAV,1139,CAV - Engenharia Qu√≠mica,MG,Belo Horizonte,2012/1,2017/1,...,Belo Horizonte,MG,NaN,80.0-90.0,Sudeste,Sudeste,1990-1999,2012,2017.0,Nao

In [2]:
# Quantidade e porcentagem de nulos por coluna
nulos = df.isnull().sum()
porcentagem = (nulos / len(df)) * 100

# Junta tudo em um DataFrame bonitinho
pd.DataFrame({'Nulos': nulos, 'Porcentagem (%)': porcentagem.round(2)})

                          Nulos  Porcentagem (%)
Identificador                 0             0.00
Ano_Nascimento               19             0.02
Sexo                          1             0.00
Campus                        0             0.00
Curso_Identificador           0             0.00
Curso                         0             0.00
UF_Nascimento               445             0.59
Municipio_Nascimento        114             0.15
Admissao                      0             0.00
Saida                         0             0.00
Codigo_Situacao_Aluno         0             0.00
Situacao_Aluno                0             0.00
Situacao_Aluno_Agrupada       0             0.00
Modalidade_Inscrita        5078             6.68
ENEM                      34628            45.53
Num_Reprovacoes               0             0.00
Raca                          0             0.00
CRA                           6             0.01
End_Municipio             14145            18.60
End_UF                    14138            18.59
Intervalo_ENEM            34628            45.53
Intervalo_CRA                40             0.05
Regiao_Nascimento           452             0.59
Regiao_End                14170            18.63
Intervalo_Ano_Nascimento     19             0.02
Ano_Admissao                  0             0.00
Ano_Saida                 11442            15.05
entrada_pandemia              0             0.00

In [3]:
# Mostra os valores √∫nicos de cada coluna
for col in df.columns:
    print(f"Coluna: {col}")
    print(df[col].unique())
    print("-" * 40)

Coluna: Identificador
[   71447   137734    71124 ... 30011449 30011462 30011463]
----------------------------------------
Coluna: Ano_Nascimento
[1989. 1998. 1991. 1992. 1996. 1993. 2002. 2000. 1984. 1999. 1983. 1987.
 2003. 2001. 1994. 1986. 1982. 1997. 1978. 2004. 1972. 1985. 1967. 1990.
 1974. 1960. 1988. 1981. 1980. 1995. 1948. 1979. 1957. 1969. 1956. 1973.
 2005. 1961. 1971. 1976. 1950. 1970. 1965. 1955. 1977. 1959. 1968. 1962.
 1966. 1953. 1975. 1964. 1963. 1947. 1952. 1958. 1946. 1954. 1951.   nan
 1949. 1942. 1941. 1944. 1940. 1945. 1938. 1900. 1943.]
----------------------------------------
Coluna: Sexo
['M' 'F' nan]
----------------------------------------
Coluna: Campus
['CAV' 'CAF' 'CRP']
----------------------------------------
Coluna: Curso_Identificador
[1110 1123 1108 1143 1139 1103 1150 1117 1102 1132 1142 1127 1113 1144
 1128 1125 1106 1141 1112 1131 1146 1109 1121 1134 1101 1116 1122 1424
 1137 1120 1111 1419 1129 1107 1135 1145 1140 1124 1126 1151 1152 1104
 1118 1114 1138 1147 1153 1130 1154 1434 1149 1401 1148 1105 1418 1423
 2101 2146 2143 2144 2145 2103 2105 2104 2106 2107 3101 3102 3103 3104
 3105 3106 3107 3108 3109 3110 3111 3112]
----------------------------------------
Coluna: Curso
['CAV - Bacharelado em Educa√ß√£o F√≠sica' 'CAV - F√≠sica'
 'CAV - Ci√™ncias Econ√¥micas' 'CAV - Licenciatura em F√≠sica'
 'CAV - Engenharia Qu√≠mica' 'CAV - Agronomia' 'CAV - Medicina'
 'CAV - Nutri√ß√£o' 'CAV - Engenharia de Agrimensura e Cartogr√°fica'
 'CAV - Geografia' 'CAV - Engenharia Mec√¢nica' 'CAV - Direito'
 'CAV - Engenharia Florestal' 'CAV - Licenciatura em Matem√°tica'
 'CAV - Arquitetura e Urbanismo' 'CAV - Qu√≠mica'
 'CAV - Engenharia Ambiental' 'CAV - Ci√™ncia da Computa√ß√£o'
 'CAV - Engenharia Civil' 'CAV - Engenharia El√©trica'
 'CAV - Licenciatura em Ci√™ncias Biol√≥gicas' 'CAV - Economia Dom√©stica'
 'CAV - Zootecnia' 'CAV - Hist√≥ria' 'CAV - Administra√ß√£o'
 'CAV - Medicina Veterin√°ria' 'CAV - Ci√™ncias Biol√≥gicas'
 'CAV - Licenciatura em Matem√°tica - EAD'
 'CAV - Secretariado Executivo Tril√≠ngue, Portugu√™s, Franc√™s, Ingl√™s'
 'CAV - Ci√™ncia e Tecnologia de Latic√≠nios'
 'CAV - Engenharia Agr√≠cola e Ambiental' 'CAV - Normal Superior'
 'CAV - Comunica√ß√£o Social' 'CAV - Engenharia de Produ√ß√£o' 'CAV - Dan√ßa'
 'CAV - Licenciatura em Qu√≠mica' 'CAV - Cooperativismo'
 'CAV - Engenharia de Agrimensura' 'CAV - Matem√°tica' 'CAV - Bioqu√≠mica'
 'CAV - Licenciatura em Educa√ß√£o do Campo - Ci√™ncias da Natureza'
 'CAV - Servi√ßo Social' 'CAV - Ci√™ncias Cont√°beis' 'CAV - Pedagogia'
 'CAV - Engenharia de Alimentos' 'CAV - Educa√ß√£o Infantil'
 'CAV - Ci√™ncias Sociais' 'CAV - Letras'
 'CAV - Licenciatura em Educa√ß√£o F√≠sica'
 'CAV - Licenciatura em Hist√≥ria - EAD'
 'CAV - Ci√™ncias Econ√¥micas - √änfase em Economia'
 'CAV - Gest√£o de Cooperativas' 'CAV - Agroneg√≥cio' 'CAV - Enfermagem'
 'CAV - Gest√£o do Agroneg√≥cio' 'CAV - Licenciatura em Pedagogia'
 'CAV - Ci√™ncias Econ√¥micas - √änfase em Agroneg√≥cio'
 'CAV - Administra√ß√£o - Habilita√ß√£o em Administra√ß√£o de Cooperativas'
 'CAF - Tecnologia em Gest√£o Ambiental'
 'CAF - Licenciatura em Ci√™ncias Biol√≥gicas'
 'CAF - Licenciatura em F√≠sica' 'CAF - Licenciatura em Matem√°tica'
 'CAF - Licenciatura em Qu√≠mica' 'CAF - Agronomia'
 'CAF - Licenciatura em Educa√ß√£o F√≠sica' 'CAF - Engenharia de Alimentos'
 'CAF - Administra√ß√£o' 'CAF - Ci√™ncia da Computa√ß√£o'
 'CRP - Administra√ß√£o - Integral' 'CRP - Administra√ß√£o - Noturno'
 'CRP - Agronomia' 'CRP - Sistemas de Informa√ß√£o - Integral'
 'CRP - Sistemas de Informa√ß√£o - Noturno'
 'CRP - Ci√™ncia e Tecnologia de Alimentos' 'CRP - Qu√≠mica'
 'CRP - Engenharia Civil' 'CRP - Ci√™ncias Cont√°beis'
 'CRP - Ci√™ncias Biol√≥gicas' 'CRP - Engenharia de Produ√ß√£o'
 'CRP - Nutri√ß√£o']
----------------------------------------
Coluna: UF_Nascimento
['MG' 'SP' 'RJ' 'ES' 'RS' 'PA' 'BA' 'DF' 'GO' nan 'AM' 'CE' 'RN' 'MA' 'AP'
 'TO' 'MS' 'MT' 'RO' 'PR' 'AL' 'PI' 'SC' 'AC' 'PE' 'SE' '  ' 'PB' 'RR' ' '
 'NJ']
----------------------------------------
Coluna: Municipio_Nascimento
['Erv√°lia' 'Sorocaba' 'Sete Lagoas' ... 'Turim' 'Marataizes' 'Pirang√≠']
----------------------------------------
Coluna: Admissao
['2009/1' '2017/1' '2010/1' '2012/1' '2014/1' '2016/1' '2021/1' '2003/1'
 '2004/1' '2006/1' '2022/1' '2018/1' '2019/1' '2013/1' '2015/1' '2011/1'
 '2022/2' '2000/1' '2023/1' '2001/1' '2010/2' '2020/1' '2007/1' '2011/2'
 '2008/2' '2002/1' '2008/1' '2017/2' '2019/2' '2005/1' '2004/2' '2006/2'
 '2012/2' '2009/2' '2016/2' '2023/2' '2018/2' '2003/2' '2021/2' '2020/2'
 '2005/2' '2015/2' '2007/2' '2014/2' '2000/2' '2002/2' '2013/2' '2001/2']
----------------------------------------
Coluna: Saida
['2013/2' '2023/2' '2009/1' '2010/2' '2017/1' '2019/1' '2021/1' '0'
 '2023/1' '2006/2' '2020/2' '2008/1' '2021/2' '2008/2' '2022/1' '2015/2'
 '2012/2' '2018/2' '2011/1' '2022/2' '2018/1' '2003/2' '2004/1' '2014/2'
 '2011/2' '2006/1' '2017/2' '2015/1' '2013/1' '2005/1' '2009/2' '2016/2'
 '2004/2' '2005/2' '2014/1' '2019/2' '2016/1' '2007/1' '2010/1' '2012/1'
 '2007/2' '2003/1' '2001/1' '2002/1' '2000/1' '2002/2' '2020/1' '2001/2'
 '2000/2']
----------------------------------------
Coluna: Codigo_Situacao_Aluno
['C' 'A' 'N' 'D' 'M' 'Q' 'T' 'K' 'F' 'S' 'X' 'G' 'J' 'I' 'B' 'W' 'Z' 'H'
 'R' 'Y' 'O']
----------------------------------------
Coluna: Situacao_Aluno
['Conclus√£o                                         '
 'Abandono                                          '
 'Normal                                            '
 'Desligamento                                      '
 'Mudan√ßa de Curso                                  '
 'Matr√≠cula Condicional/Reconsidera√ß√£o Desligamento '
 'Transfer√™ncia                                     '
 'Trancamento                                       '
 'Falecimento                                       '
 'Anula√ß√£o de Matr√≠cula                             '
 'Exclus√£o                                          '
 'Afastamento/Interc√¢mbio                           '
 'Matr√≠cula Suspensa Temporariamente                '
 'Concluinte (relat√≥rio n√£o analisado)              '
 'Concluiu as exig√™ncias do curso (n√£o colou grau)  '
 'Afastamento Especial                              '
 'Trancamento por Motivo de Sa√∫de                   '
 'Habilita√ß√£o                                       '
 'Afastamento/Reconsidera√ß√£o de Desligamento        '
 'Afastamento                                       '
 'Matr√≠cula Condicional/Reconsidera√ß√£o desligamento '
 'Concluindo (n√£o colou grau)                       '
 'Estudante em abandono do curso                    '
 'Concluinte (n√£o colou grau)                       '
 'Estudante em mobilidade                           '
 'Concluinte (Relat√≥rio N√£o Analisado)              '
 'Desligamento com processo aberto                  ']
----------------------------------------
Coluna: Situacao_Aluno_Agrupada
['Conclus√£o' 'Evas√£o' 'Matriculado' 'Reten√ß√£o']
----------------------------------------
Coluna: Modalidade_Inscrita
[ 0.  9.  5.  1.  3.  7. nan  4.  8.  6.  2.]
----------------------------------------
Coluna: ENEM
[ nan 658. 639. 623. 748. 660. 528. 783. 585. 459. 723. 707. 661. 671.
 690. 738. 683. 634. 706. 722. 612. 669. 801. 597. 664. 593. 678. 746.
 668. 685. 657. 642. 631. 641. 610. 699. 681. 643. 601. 638. 666. 697.
 628. 695. 694. 517. 552. 645. 563. 460. 490. 598. 493. 545. 622. 568.
 679. 716. 567. 588. 663. 626. 575. 548. 698. 635. 717. 606. 684. 604.
 633. 696. 674. 758. 615. 621. 536. 700. 518. 653. 701. 605. 591. 520.
 659. 590. 691. 689. 556. 712. 806. 682. 731. 636. 736. 632. 677. 637.
 654. 656. 640. 439. 742. 675. 589. 599. 805. 613. 751. 550. 688. 646.
 648. 618. 655. 630. 676. 624. 595. 749. 747. 734. 487. 564. 754. 533.
 587. 514. 594. 573. 733. 650. 667. 600. 627. 687. 532. 507. 670. 651.
 619. 616. 702. 644. 629. 559. 720. 724. 680. 732. 718. 710. 488. 609.
 539. 584. 513. 561. 739. 693. 565. 498. 715. 586. 719. 562. 596. 554.
 495. 580. 665. 662. 625. 692. 547. 649. 570. 725. 744. 463. 574. 525.
 765. 672. 551. 709. 652. 704. 741. 569. 705. 711. 713. 560. 537. 608.
 521. 566. 721. 726. 614. 543. 577. 333. 508. 558. 757. 579. 761. 504.
 602. 482. 557. 571. 611. 509. 542. 572. 522. 786. 512. 703. 483. 620.
 762. 729. 540. 549. 474. 728. 756. 686. 647. 727. 617. 788. 804. 760.
 526. 787. 794. 673. 398. 553. 774. 555. 607. 603. 730. 494. 802. 534.
 576. 803. 405. 530. 546. 708. 535. 538. 592. 789. 714. 499. 578. 489.
 764. 768. 505. 740. 492. 582. 766. 465. 544. 759. 750. 476. 523. 790.
 531. 583. 519. 773. 511. 484. 450. 442. 737. 767. 541. 470. 793. 467.
 529. 469. 770. 480. 581. 468. 496. 416. 763. 753. 347. 755. 743. 473.
 359. 800. 445. 797. 502. 477. 771. 735. 404. 527. 422. 515. 785. 485.
 448. 393. 418. 424. 326. 449. 409. 510. 524. 441. 501. 486. 401. 752.
 421. 795. 772. 431. 799. 455. 475. 818. 443. 497. 745. 779. 500. 402.
 775. 440. 427. 434. 811. 415. 506. 472. 408. 406. 791. 426. 479. 776.
 456. 432. 464. 782. 478. 451. 503. 446. 777. 396. 412. 461. 810. 300.
 784. 452. 778. 792. 516. 798. 436. 466. 796. 429. 444. 458. 781. 425.
 453. 373. 821. 491. 809. 410. 428. 820. 780. 435. 815. 407. 462. 388.
 306. 481. 377. 414. 387. 447. 454. 433. 807. 430. 320. 769. 420. 423.
 403. 417. 471. 395. 341. 457. 419. 394. 337. 847. 438. 413. 214. 392.
 323. 808. 307. 332. 391. 411. 400. 345. 437. 383. 384. 357. 372. 274.
 816. 380. 386. 390. 397. 355. 277. 253. 360. 369. 385. 376. 318. 399.
 375.]
----------------------------------------
Coluna: Num_Reprovacoes
[ 0  6  5 10  2  4 15 12  1 19 20 11  9 30 13  3  8 17 21  7 18 16 14 25
 27 34 22 24 31 32 44 26 23 28 29 37 35 60 93 41 36 59 33 46 47 43 38 65
 40 80 68 39 82 76 58 49 42 57 70 56]
----------------------------------------
Coluna: Raca
['Pardo(a)' 'Informa√ß√£o n√£o dispon√≠vel' 'Branco(a)' 'Preto(a)'
 'Amarelo(a)' 'Ind√≠gena']
----------------------------------------
Coluna: CRA
[ 84.  71.   0.  15.  80.  82.  69.  23.  79.  55.  89.  83.  70.  50.
  90.  54.  41.  56.  52.  49.  62.  68.  63.  77.  78.  32.  46.  74.
  94.  76.  73.  72.  18.  85.  30.  75.  81.  66.  39.  60.  58.  61.
  86.  35.  37.  57.  45.  13.  38.  93.  11.  43.  26.  88.   6.  91.
  65.  48.  53.  67.  20.  27.  44.  16.  92.  64.  21.  22.   4.  29.
   8.  36.  42.  34.  87.  96.  12.  19.  51.  28.  17.  59.  95.  24.
  31.   1.   3.  10.  47.   2.  40.   9.  97.   5.  25.  14.  33.   7.
  98. 100.  99.  nan]
----------------------------------------
Coluna: End_Municipio
['Ervalia' 'Votorantim' 'Ouro Branco' ... 'Ferraz de Vasconcelos'
 'Lic√≠nio de Almeida' 'Vi√ßosa do Cear√°']
----------------------------------------
Coluna: End_UF
['MG' 'SP' 'RJ' 'ES' 'RS' nan 'BA' 'PA' 'RO' 'GO' 'TO' 'PR' 'DF' 'RN' 'MA'
 'AP' 'MT' 'SC' 'AM' 'MS' 'AC' 'SE' 'PB' 'CE' 'PE' 'AL' '\xa0' 'ZZ' 'PI'
 '\xa0\xa0' 'RR' '\xa0 ' '  ' '0']
----------------------------------------
Coluna: Intervalo_ENEM
[nan '600.0-700.0' '700.0-800.0' '500.0-600.0' '400.0-500.0' '800.0-900.0'
 '300.0-400.0' '200.0-300.0']
----------------------------------------
Coluna: Intervalo_CRA
['80.0-90.0' '70.0-80.0' '0-10' '10.0-20.0' '60.0-70.0' '20.0-30.0'
 '50.0-60.0' '90.0-100.0' '40.0-50.0' '30.0-40.0' nan]
----------------------------------------
Coluna: Regiao_Nascimento
['Sudeste' 'Sul' 'Norte' 'Nordeste' 'Centro-Oeste' nan]
----------------------------------------
Coluna: Regiao_End
['Sudeste' 'Sul' nan 'Nordeste' 'Norte' 'Centro-Oeste']
----------------------------------------
Coluna: Intervalo_Ano_Nascimento
['1980-1989' '1990-1999' '2000-2009' '1970-1979' '1960-1969' '1940-1949'
 '1950-1959' nan '1930-1939' '1900-1909']
----------------------------------------
Coluna: Ano_Admissao
[2009 2017 2010 2012 2014 2016 2021 2003 2004 2006 2022 2018 2019 2013
 2015 2011 2000 2023 2001 2020 2007 2008 2002 2005]
----------------------------------------
Coluna: Ano_Saida
[2013. 2023. 2009. 2010. 2017. 2019. 2021.   nan 2006. 2020. 2008. 2022.
 2015. 2012. 2018. 2011. 2003. 2004. 2014. 2005. 2016. 2007. 2001. 2002.
 2000.]
----------------------------------------
Coluna: entrada_pandemia
['Nao' 'Sim']
----------------------------------------

### 2Ô∏è‚É£ Cria√ß√£o da nova Base de Dados

In [4]:
# Lista dos cursos desejados
cursos_TI = [
    'CAF - Ci√™ncia da Computa√ß√£o',
    'CRP - Sistemas de Informa√ß√£o - Integral',
    'CRP - Sistemas de Informa√ß√£o - Noturno',
    'CAV - Ci√™ncia da Computa√ß√£o'
]

# Filtra as linhas em que o valor da coluna 'Curso' est√° na lista
df_comp = df[df['Curso'].isin(cursos_TI)]

# Salva em um novo arquivo Excel
df_comp.to_excel('dados_UFV_comp_VD.xlsx', index=False)

In [5]:
df_comp.head()

,Identificador,Ano_Nascimento,Sexo,Campus,Curso_Identificador,Curso,UF_Nascimento,Municipio_Nascimento,Admissao,Saida,...,End_Municipio,End_UF,Intervalo_ENEM,Intervalo_CRA,Regiao_Nascimento,Regiao_End,Intervalo_Ano_Nascimento,Ano_Admissao,Ano_Saida,entrada_pandemia
19,112343,1996.0,M,CAV,1141,CAV - Ci√™ncia da Computa√ß√£o,MG,Coronel Fabriciano,2015/1,2023/2,...,Belo Oriente,MG,600.0-700.0,50.0-60.0,Sudeste,Sudeste,1990-1999,2015,2023.0,Nao
25,128409,1996.0,F,CAV,1141,CAV - Ci√™ncia da Computa√ß√£o,MG,Ipatinga,2016/1,2022/2,...,Ipatinga,MG,600.0-700.0,60.0-70.0,Sudeste,Sudeste,1990-1999,2016,2022.0,Nao
27,139167,1982.0,M,CAV,1141,CAV - Ci√™ncia da Computa√ß√£o,MG,Coronel Fabriciano,2017/1,2017/1,...,Timoteo,MG,700.0-800.0,0-10,Sudeste,Sudeste,1980-1989,2017,2017.0,Nao
55,82002,1993.0,M,CAV,1141,CAV - Ci√™ncia da Computa√ß√£o,BA,Cruz das Almas,2011/1,2011/1,...,Cruz das Almas,BA,NaN,60.0-70.0,Nordeste,Nordeste,1990-1999,2011,2011.0,Nao
127,112368,1996.0,M,CAV,1141,CAV - Ci√™ncia da Computa√ß√£o,MG,Vi√ßosa,2015/1,2021/2,...,Vi√ßosa,MG,NaN,50.0-60.0,Sudeste,Sudeste,1990-1999,2015,2021.0,Nao

In [6]:
# Cria um DataFrame com as contagens
contagem_cursos = df_comp['Curso'].value_counts().reset_index()
contagem_cursos.columns = ['Curso', 'Quantidade']
contagem_cursos

                                     Curso  Quantidade
0              CAV - Ci√™ncia da Computa√ß√£o        1111
1   CRP - Sistemas de Informa√ß√£o - Noturno         798
2  CRP - Sistemas de Informa√ß√£o - Integral         730
3              CAF - Ci√™ncia da Computa√ß√£o         627